// Pure data for measures: unit dimensions, optional default factors, and the
// volume-unit definitions for each measurement system.
//
// The subject in `300g butter in cups` is a free-form label — it needs no
// dataset. A known label can supply a conversion factor (DEFAULT_FACTORS), but
// any other label still works: the label is informational and the conversion
// falls back to a default density. See js/eval/measures.js.

// Units grouped by the dimension they measure. Only used to tell a unit apart
// from a subject label and to decide whether a conversion needs a factor.
export const DIMENSIONS = {
  mass: new Set([
    'g',
    'gram',
    'grams',
    'kg',
    'kilogram',
    'kilograms',
    'mg',
    'milligram',
    'milligrams',
    'mcg',
    'ug',
    'µg',
    'oz',
    'ounce',
    'ounces',
    'lb',
    'lbs',
    'pound',
    'pounds',
    'lbm',
    'st',
    'stone',
    'stones',
    't',
    'tonne',
    'tonnes',
    'ton',
    'tons',
    'grain',
    'grains',
    'dram',
    'drams',
    'carat',
    'carats',
    'cwt',
  ]),
  volume: new Set([
    'ml',
    'milliliter',
    'milliliters',
    'millilitre',
    'millilitres',
    'cl',
    'dl',
    'l',
    'liter',
    'liters',
    'litre',
    'litres',
    'kl',
    'cc',
    'm3',
    'cuin',
    'cuft',
    'cuyd',
    'cup',
    'cups',
    'tsp',
    'teaspoon',
    'teaspoons',
    'tbsp',
    'tablespoon',
    'tablespoons',
    'floz',
    'fluidounce',
    'fluidounces',
    'pint',
    'pints',
    'quart',
    'quarts',
    'gallon',
    'gallons',
    'minim',
    'fluiddram',
    'gill',
    'drop',
    'barrel',
    'bbl',
    'hogshead',
  ]),
  time: new Set([
    'ns',
    'us',
    'µs',
    'ms',
    's',
    'sec',
    'secs',
    'second',
    'seconds',
    'min',
    'mins',
    'minute',
    'minutes',
    'h',
    'hr',
    'hrs',
    'hour',
    'hours',
    'day',
    'days',
    'week',
    'weeks',
    'month',
    'months',
    'year',
    'years',
    'decade',
    'decades',
    'century',
    'centuries',
    'millennium',
    'millennia',
  ]),
  data: new Set([
    'b',
    'bit',
    'bits',
    'byte',
    'bytes',
    'kb',
    'kB',
    'KB',
    'mb',
    'MB',
    'gb',
    'GB',
    'tb',
    'TB',
    'pb',
    'PB',
    'kib',
    'KiB',
    'mib',
    'MiB',
    'gib',
    'GiB',
    'tib',
    'TiB',
  ]),
  energy: new Set([
    'j',
    'joule',
    'joules',
    'kj',
    'kJ',
    'mj',
    'MJ',
    'gj',
    'GJ',
    'wh',
    'Wh',
    'kwh',
    'kWh',
    'mwh',
    'MWh',
    'gwh',
    'GWh',
    'cal',
    'kcal',
    'kCal',
    'btu',
    'BTU',
    'ev',
    'eV',
    'erg',
  ]),
  distance: new Set([
    'nm',
    'µm',
    'mm',
    'cm',
    'dm',
    'm',
    'meter',
    'meters',
    'metre',
    'metres',
    'km',
    'in',
    'inch',
    'inches',
    'ft',
    'foot',
    'feet',
    'yd',
    'yard',
    'yards',
    'mi',
    'mile',
    'miles',
    'fur',
    'furlong',
    'ftm',
    'fathom',
    'nm',
    'ly',
  ]),
};

const UNIT_DIMENSION = new Map();
for (const [dimension, units] of Object.entries(DIMENSIONS)) {
  for (const unit of units) UNIT_DIMENSION.set(unit.toLowerCase(), dimension);
}

export function unitDimension(token) {
  return UNIT_DIMENSION.get(String(token).toLowerCase()) ?? null;
}

export function isUnit(token) {
  return unitDimension(token) !== null;
}

const TRAILING_UNIT = /([A-Za-zµ][A-Za-zµ]*)\s*$/;

// The unit symbol at the end of a value (`300g` -> `g`, `10 cups` -> `cups`).
export function trailingUnit(text) {
  const match = TRAILING_UNIT.exec(String(text).trim());
  return match ? match[1] : null;
}

export function trailingDimension(text) {
  const unit = trailingUnit(text);
  return unit ? unitDimension(unit) : null;
}

// Optional convenience factors. A subject missing from here still works — the
// label is free-form and the evaluator falls back to a default density.
export const DEFAULT_FACTORS = {
  // Cooking — density, grams per millilitre.
  water: '1 g/ml',
  milk: '1.03 g/ml',
  buttermilk: '1.03 g/ml',
  'evaporated milk': '1.07 g/ml',
  'condensed milk': '1.28 g/ml',
  'almond milk': '1 g/ml',
  'coconut milk': '0.98 g/ml',
  'heavy cream': '1 g/ml',
  'sour cream': '1 g/ml',
  cream: '1 g/ml',
  yogurt: '1.03 g/ml',
  butter: '0.911 g/ml',
  margarine: '0.96 g/ml',
  'olive oil': '0.918 g/ml',
  'vegetable oil': '0.92 g/ml',
  'canola oil': '0.92 g/ml',
  'sunflower oil': '0.92 g/ml',
  'sesame oil': '0.92 g/ml',
  'coconut oil': '0.925 g/ml',
  oil: '0.92 g/ml',
  honey: '1.42 g/ml',
  'maple syrup': '1.33 g/ml',
  molasses: '1.4 g/ml',
  'corn syrup': '1.38 g/ml',
  sugar: '0.845 g/ml',
  'brown sugar': '0.93 g/ml',
  'powdered sugar': '0.56 g/ml',
  'coconut sugar': '0.8 g/ml',
  flour: '0.53 g/ml',
  'bread flour': '0.55 g/ml',
  'whole wheat flour': '0.55 g/ml',
  'almond flour': '0.4 g/ml',
  'cocoa powder': '0.52 g/ml',
  cornstarch: '0.63 g/ml',
  'baking powder': '0.9 g/ml',
  'baking soda': '0.9 g/ml',
  salt: '1.2 g/ml',
  rice: '0.85 g/ml',
  oats: '0.41 g/ml',
  'peanut butter': '1.08 g/ml',
  nutella: '1.24 g/ml',
  jam: '1.3 g/ml',
  ketchup: '1.14 g/ml',
  mayonnaise: '0.91 g/ml',
  mustard: '1.05 g/ml',
  'soy sauce': '1.15 g/ml',
  vinegar: '1.01 g/ml',
  'milk powder': '0.5 g/ml',
  // Materials — density, grams per millilitre.
  gold: '19.32 g/ml',
  silver: '10.49 g/ml',
  copper: '8.96 g/ml',
  lead: '11.34 g/ml',
  iron: '7.87 g/ml',
  aluminium: '2.7 g/ml',
  steel: '7.85 g/ml',
  mercury: '13.53 g/ml',
  ethanol: '0.789 g/ml',
  glycerin: '1.26 g/ml',
  sand: '1.6 g/ml',
  concrete: '2.4 g/ml',
  // Fuels — energy density, kilowatt-hours per litre.
  petrol: '9.5 kWh/l',
  gasoline: '9.5 kWh/l',
  diesel: '10.7 kWh/l',
  kerosene: '10.3 kWh/l',
  lpg: '7.1 kWh/l',
  // Media — bitrate, gigabytes per hour.
  '4k video': '7.2 GB/h',
  '1080p video': '1.5 GB/h',
  '720p video': '0.9 GB/h',
  audio: '0.07 GB/h',
};

// A generic label with no known factor falls back to water.
export const DEFAULT_DENSITY = '1 g/ml';

export const MEASUREMENT_SYSTEMS = ['metric', 'us', 'imperial'];
export const DEFAULT_MEASUREMENT_SYSTEM = 'metric';

// Volume units per measurement system, in millilitres. `cup` is included in
// every system (imperial cup = 284.13 ml).
export const VOLUME_UNITS = {
  metric: {
    teaspoon: { definition: '5 ml', aliases: ['tsp'] },
    tablespoon: { definition: '15 ml', aliases: ['tbsp'] },
    fluidounce: { definition: '30 ml', aliases: ['floz'] },
    cup: { definition: '250 ml', aliases: ['cups'] },
    pint: { definition: '500 ml', aliases: ['pints', 'pt'] },
    quart: { definition: '1 l', aliases: ['quarts', 'qt'] },
    gallon: { definition: '4 l', aliases: ['gallons', 'gal'] },
  },
  us: {
    teaspoon: { definition: '4.92892159375 ml', aliases: ['tsp'] },
    tablespoon: { definition: '14.78676478125 ml', aliases: ['tbsp'] },
    fluidounce: { definition: '29.5735295625 ml', aliases: ['floz'] },
    cup: { definition: '236.5882365 ml', aliases: ['cups'] },
    pint: { definition: '473.176473 ml', aliases: ['pints', 'pt'] },
    quart: { definition: '946.352946 ml', aliases: ['quarts', 'qt'] },
    gallon: { definition: '3785.411784 ml', aliases: ['gallons', 'gal'] },
  },
  imperial: {
    teaspoon: { definition: '5.919388020833 ml', aliases: ['tsp'] },
    tablespoon: { definition: '17.7581640625 ml', aliases: ['tbsp'] },
    fluidounce: { definition: '28.4130625 ml', aliases: ['floz'] },
    cup: { definition: '284.130625 ml', aliases: ['cups'] },
    pint: { definition: '568.26125 ml', aliases: ['pints', 'pt'] },
    quart: { definition: '1136.5225 ml', aliases: ['quarts', 'qt'] },
    gallon: { definition: '4546.09 ml', aliases: ['gallons', 'gal'] },
  },
};
