// Build the Help and Examples content modules from the Markdown sources in
// src/. Run with `make -C js/i18n` (or `npm run build:i18n`). The generated
// files are committed and lazy-loaded by the modals, like the mathjs bundle.
import { marked } from 'npm:marked@15';

const ROOT = new URL('.', import.meta.url).pathname;
const AREAS = ['help', 'examples'];
const LANGS = ['en', 'pt', 'es'];

function escapeHtml(text) {
  return String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function escapeAttr(text) {
  return escapeHtml(text).replace(/"/g, '&quot;');
}

// ```calc <hint>
// <expression>
// ```
// becomes the clickable example chip the modal wires up (`examples.js`).
marked.use({
  renderer: {
    code(token) {
      const lang = token.lang || '';
      if (!lang.startsWith('calc')) return false;
      const hint = lang.slice('calc'.length).trim();
      const expr = token.text.replace(/\n$/, '');
      const hintHtml = hint ? `<span class="help-returns">${escapeHtml(hint)}</span>` : '';
      return (
        `<div class="help-example" data-expr="${escapeAttr(expr)}" ` +
        `tabindex="0" role="button"><code></code>${hintHtml}</div>`
      );
    },
  },
});

function slug(text) {
  return text
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/&/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function renderMarkdown(md) {
  return marked.parse(md).trim();
}

function parse(md, prefix) {
  const parts = md.split(/^## /m);
  const introMd = parts.shift().trim();
  const sections = parts.map((part) => {
    const newline = part.indexOf('\n');
    const nav = (newline === -1 ? part : part.slice(0, newline)).trim();
    const body = newline === -1 ? '' : part.slice(newline + 1);
    return { id: `${prefix}${slug(nav)}`, nav, html: renderMarkdown(body) };
  });
  return { intro: introMd ? renderMarkdown(introMd) : '', sections };
}

for (const area of AREAS) {
  for (const lang of LANGS) {
    const source = Deno.readTextFileSync(`${ROOT}src/${area}.${lang}.md`);
    const data = parse(source, `${area}-`);
    const banner =
      `// Generated by \`make -C js/i18n\` from src/${area}.${lang}.md. ` +
      'Edit the Markdown, not this file.\n';
    Deno.mkdirSync(`${ROOT}${area}`, { recursive: true });
    Deno.writeTextFileSync(
      `${ROOT}${area}/${lang}.js`,
      `${banner}export default ${JSON.stringify(data, null, 2)};\n`
    );
    console.log(`${area}.${lang}.js`);
  }
}
