// Generated by `make -C js/i18n` from src/examples.en.md. Edit the Markdown, not this file.
export default {
  "intro": "<p>Ready-made calculations. Click one to add it to the editor and edit the values.</p>",
  "sections": [
    {
      "id": "examples-restaurant-payment-split",
      "nav": "Restaurant payment split",
      "html": "<p>Split a bill evenly, including the tip.</p>\n<div class=\"help-example\" data-expr=\"bill = 120\ntip = bill * 10%\npeople = 4\n(bill + tip) / people\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">last line returns 33</span></div>"
    },
    {
      "id": "examples-restaurant-bill-split-with-tags",
      "nav": "Restaurant bill split with tags",
      "html": "<p>Split a bar bill between four people. Write each item&#39;s full amount and tag everyone who shared it; each tag gets an equal share, while the group total keeps the full price.</p>\n<div class=\"help-example\" data-expr=\"At the bar:\npotato: 20 #name1 #name2 #name3\nburger: 2 * 50 #name1 #name3\nbeer: 160 #name1 #name2 #name3 #name4\nend\n\n#name1\n#name2\n#name3\n#name4\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">each #name returns a person's total</span></div>"
    },
    {
      "id": "examples-scale-a-recipe",
      "nav": "Scale a recipe",
      "html": "<p>Scale ingredient amounts to a different number of servings, converting between volume and mass as you go.</p>\n<div class=\"help-example\" data-expr=\"scale = 6 / 4\nscale * 2 cups flour in grams\nscale * 300g butter in cups\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">397.5 g flour; ≈ 1.98 cups butter</span></div>"
    },
    {
      "id": "examples-hours-of-work",
      "nav": "Hours of work",
      "html": "<p>Gross pay for a given number of hours at an hourly rate.</p>\n<div class=\"help-example\" data-expr=\"hours = 40\nrate = 25\nhours * rate\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">last line returns 1000</span></div>"
    },
    {
      "id": "examples-unit-price-comparison",
      "nav": "Unit price comparison",
      "html": "<p>Compare two packs by their price per 100 g.</p>\n<div class=\"help-example\" data-expr=\"small = 3.99 / 500 * 100\nlarge = 6.49 / 1000 * 100\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">0.798 vs 0.649 — the large pack is cheaper</span></div>"
    },
    {
      "id": "examples-percentage-discount",
      "nav": "Percentage discount",
      "html": "<p>Price after a percentage discount.</p>\n<div class=\"help-example\" data-expr=\"price = 80\ndiscount = 15%\nprice - price * discount\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">last line returns 68</span></div>"
    },
    {
      "id": "examples-savings-goal",
      "nav": "Savings goal",
      "html": "<p>How many months to reach a goal at a fixed monthly amount.</p>\n<div class=\"help-example\" data-expr=\"goal = 5000\nmonthly = 250\ngoal / monthly\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">last line returns 20 months</span></div>"
    },
    {
      "id": "examples-simple-interest",
      "nav": "Simple interest",
      "html": "<p>Interest earned on a principal over a number of years.</p>\n<div class=\"help-example\" data-expr=\"principal = 1000\nrate = 5%\nyears = 3\nprincipal * rate * years\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">last line returns 150</span></div>"
    },
    {
      "id": "examples-fuel-cost-for-a-trip",
      "nav": "Fuel cost for a trip",
      "html": "<p>Cost of fuel for a distance at a given consumption and price per litre.</p>\n<div class=\"help-example\" data-expr=\"distance = 300\nconsumption = 8\nfuelPrice = 1.7\ndistance / 100 * consumption * fuelPrice\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">last line returns 40.8</span></div>"
    },
    {
      "id": "examples-running-pace",
      "nav": "Running pace",
      "html": "<p>Your pace per kilometre, then the finish time for a longer race at that pace.</p>\n<div class=\"help-example\" data-expr=\"# Pace per km\n5 km in 25 min\n# Half-marathon at that pace\n21.1 km * prev\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">05:00/km, then 105.5 min</span></div>"
    },
    {
      "id": "examples-upload-time",
      "nav": "Upload time",
      "html": "<p>How long a file takes to upload at a given speed.</p>\n<div class=\"help-example\" data-expr=\"time to upload 3 GB at 10 MB/s\ntime to upload 3 GB at 2 MB/s\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">300 s, then 1,500 s</span></div>"
    },
    {
      "id": "examples-body-mass-index",
      "nav": "Body Mass Index",
      "html": "<p>BMI from weight in kg and height in metres.</p>\n<div class=\"help-example\" data-expr=\"weight = 70\nheight = 1.75\nweight / height ^ 2\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">last line returns ≈ 22.86</span></div>"
    },
    {
      "id": "examples-age-and-elapsed-time",
      "nav": "Age and elapsed time",
      "html": "<p>Measure the span from a date to today — first as calendar years, months and days, then as a plain day count.</p>\n<div class=\"help-example\" data-expr=\"1990-04-01 to today\ndays since 1990-04-01\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">exact age, then total days</span></div>"
    },
    {
      "id": "examples-countdown-to-a-birthday",
      "nav": "Countdown to a birthday",
      "html": "<p>Days left until the next time a date comes around. Change the month and day to your own.</p>\n<div class=\"help-example\" data-expr=\"birthday = June 21\ndays until birthday\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">days until the next 21 June</span></div>"
    },
    {
      "id": "examples-fuel-cost-with-units",
      "nav": "Fuel cost with units",
      "html": "<p>The consumption and the price per litre cancel down to a total cost.</p>\n<div class=\"help-example\" data-expr=\"trip = 350 km\neconomy = 7 l / 100 km\nprice = 1.70 EUR/l\ntrip * economy * price\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">€ 41.65</span></div>"
    },
    {
      "id": "examples-overtime-pay",
      "nav": "Overtime pay",
      "html": "<p>Regular hours at the base rate, plus the extra hours at time and a half.</p>\n<div class=\"help-example\" data-expr=\"worked = 45\nrate = 25 USD/hour\nregular = 40 hours * rate\novertime = (worked - 40) hours * rate * 1.5\nregular + overtime\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">US$ 1,187.5 for 40 h + 5 h overtime</span></div>"
    },
    {
      "id": "examples-meeting-length",
      "nav": "Meeting length",
      "html": "<p>Add the clock-time interval of each meeting and show the total as a timespan.</p>\n<div class=\"help-example\" data-expr=\"standup = 9:00 am to 9:15 am\nreview = 2:00 pm to 3:30 pm\nstandup + review as timespan\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">1 hour 45 minutes total</span></div>"
    },
    {
      "id": "examples-clock-reminders",
      "nav": "Clock reminders",
      "html": "<p>Get a clock time a fixed offset after an anchor time — handy for alarms and reminders.</p>\n<div class=\"help-example\" data-expr=\"wake = 6:30 am\nwake + 45 minutes\nwake + 8 hours\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">07:15 and 14:30</span></div>"
    },
    {
      "id": "examples-household-budget-by-category",
      "nav": "Household budget by category",
      "html": "<p>Tag each expense with a category; a line that is only the tag totals that category, and tags add up too.</p>\n<div class=\"help-example\" data-expr=\"Budget:\nrent: 1200 #home\nutilities: 150 #home\ngroceries: 480 #living\ntransport: 120 #living\nend\n#home\n#living\n#home + #living\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">each #tag is a category total; the last adds them up</span></div>"
    }
  ]
};
