// Generated by `make -C js/i18n` from src/examples.es.md. Edit the Markdown, not this file.
export default {
  "intro": "<p>Cálculos ya hechos. Haz clic en uno para añadirlo al editor y edita los valores.</p>",
  "sections": [
    {
      "id": "examples-dividir-la-cuenta-del-restaurante",
      "nav": "Dividir la cuenta del restaurante",
      "html": "<p>Divide una cuenta a partes iguales, incluida la propina.</p>\n<div class=\"help-example\" data-expr=\"bill = 120\ntip = bill * 10%\npeople = 4\n(bill + tip) / people\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">la última línea devuelve 33</span></div>"
    },
    {
      "id": "examples-dividir-la-cuenta-del-bar-con-tags",
      "nav": "Dividir la cuenta del bar con tags",
      "html": "<p>Divide una cuenta de bar entre cuatro personas. Escribe el importe total de cada artículo y etiqueta a todos los que lo compartieron; cada tag recibe la misma parte, mientras que el total del grupo conserva el precio completo.</p>\n<div class=\"help-example\" data-expr=\"At the bar:\npotato: 20 #name1 #name2 #name3\nburger: 2 * 50 #name1 #name3\nbeer: 160 #name1 #name2 #name3 #name4\nend\n\n#name1\n#name2\n#name3\n#name4\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">cada #nombre devuelve el total de una persona</span></div>"
    },
    {
      "id": "examples-escalar-una-receta",
      "nav": "Escalar una receta",
      "html": "<p>Escala las cantidades de los ingredientes para un número distinto de raciones, convirtiendo entre volumen y masa sobre la marcha.</p>\n<div class=\"help-example\" data-expr=\"scale = 6 / 4\nscale * 2 cups flour in grams\nscale * 300g butter in cups\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">397.5 g de harina; ≈ 1.98 cups de mantequilla</span></div>"
    },
    {
      "id": "examples-horas-de-trabajo",
      "nav": "Horas de trabajo",
      "html": "<p>Pago bruto por un número de horas a una tarifa por hora.</p>\n<div class=\"help-example\" data-expr=\"hours = 40\nrate = 25\nhours * rate\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">la última línea devuelve 1000</span></div>"
    },
    {
      "id": "examples-comparacion-de-precio-por-unidad",
      "nav": "Comparación de precio por unidad",
      "html": "<p>Compara dos paquetes por su precio por 100 g.</p>\n<div class=\"help-example\" data-expr=\"small = 3.99 / 500 * 100\nlarge = 6.49 / 1000 * 100\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">0.798 vs 0.649 — el paquete grande es más barato</span></div>"
    },
    {
      "id": "examples-descuento-porcentual",
      "nav": "Descuento porcentual",
      "html": "<p>Precio tras un descuento porcentual.</p>\n<div class=\"help-example\" data-expr=\"price = 80\ndiscount = 15%\nprice - price * discount\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">la última línea devuelve 68</span></div>"
    },
    {
      "id": "examples-meta-de-ahorro",
      "nav": "Meta de ahorro",
      "html": "<p>Cuántos meses para alcanzar una meta con un importe mensual fijo.</p>\n<div class=\"help-example\" data-expr=\"goal = 5000\nmonthly = 250\ngoal / monthly\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">la última línea devuelve 20 months</span></div>"
    },
    {
      "id": "examples-interes-simple",
      "nav": "Interés simple",
      "html": "<p>Interés ganado sobre un capital durante varios años.</p>\n<div class=\"help-example\" data-expr=\"principal = 1000\nrate = 5%\nyears = 3\nprincipal * rate * years\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">la última línea devuelve 150</span></div>"
    },
    {
      "id": "examples-coste-de-combustible-de-un-viaje",
      "nav": "Coste de combustible de un viaje",
      "html": "<p>Coste del combustible para una distancia con un consumo y un precio por litro dados.</p>\n<div class=\"help-example\" data-expr=\"distance = 300\nconsumption = 8\nfuelPrice = 1.7\ndistance / 100 * consumption * fuelPrice\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">la última línea devuelve 40.8</span></div>"
    },
    {
      "id": "examples-ritmo-de-carrera",
      "nav": "Ritmo de carrera",
      "html": "<p>Tu ritmo por kilómetro y, después, el tiempo de llegada para una carrera más larga a ese ritmo.</p>\n<div class=\"help-example\" data-expr=\"# Pace per km\n5 km in 25 min\n# Half-marathon at that pace\n21.1 km * prev\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">05:00/km, luego 105.5 min</span></div>"
    },
    {
      "id": "examples-tiempo-de-subida",
      "nav": "Tiempo de subida",
      "html": "<p>Cuánto tarda un archivo en subirse a una velocidad dada.</p>\n<div class=\"help-example\" data-expr=\"time to upload 3 GB at 10 MB/s\ntime to upload 3 GB at 2 MB/s\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">300 s, luego 1,500 s</span></div>"
    },
    {
      "id": "examples-indice-de-masa-corporal",
      "nav": "Índice de Masa Corporal",
      "html": "<p>IMC a partir del peso en kg y la altura en metros.</p>\n<div class=\"help-example\" data-expr=\"weight = 70\nheight = 1.75\nweight / height ^ 2\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">la última línea devuelve ≈ 22.86</span></div>"
    },
    {
      "id": "examples-edad-y-tiempo-transcurrido",
      "nav": "Edad y tiempo transcurrido",
      "html": "<p>Mide el intervalo desde una fecha hasta hoy — primero en años, meses y días, y luego en número de días.</p>\n<div class=\"help-example\" data-expr=\"1990-04-01 to today\ndays since 1990-04-01\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">edad exacta, luego total de días</span></div>"
    },
    {
      "id": "examples-cuenta-atras-para-un-cumpleanos",
      "nav": "Cuenta atrás para un cumpleaños",
      "html": "<p>Días que faltan hasta la próxima vez que llega una fecha. Cambia el mes y el día por los tuyos.</p>\n<div class=\"help-example\" data-expr=\"birthday = June 21\ndays until birthday\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">días hasta el próximo 21 June</span></div>"
    },
    {
      "id": "examples-coste-de-combustible-con-unidades",
      "nav": "Coste de combustible con unidades",
      "html": "<p>El consumo y el precio por litro se cancelan hasta un coste total.</p>\n<div class=\"help-example\" data-expr=\"trip = 350 km\neconomy = 7 l / 100 km\nprice = 1.70 EUR/l\ntrip * economy * price\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">€ 41.65</span></div>"
    },
    {
      "id": "examples-pago-de-horas-extra",
      "nav": "Pago de horas extra",
      "html": "<p>Horas normales a la tarifa base, más las horas extra a tiempo y medio.</p>\n<div class=\"help-example\" data-expr=\"worked = 45\nrate = 25 USD/hour\nregular = 40 hours * rate\novertime = (worked - 40) hours * rate * 1.5\nregular + overtime\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">US$ 1,187.5 por 40 h + 5 h extra</span></div>"
    },
    {
      "id": "examples-duracion-de-la-reunion",
      "nav": "Duración de la reunión",
      "html": "<p>Suma el intervalo horario de cada reunión y muestra el total como un timespan.</p>\n<div class=\"help-example\" data-expr=\"standup = 9:00 am to 9:15 am\nreview = 2:00 pm to 3:30 pm\nstandup + review as timespan\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">1 hour 45 minutes en total</span></div>"
    },
    {
      "id": "examples-recordatorios-de-hora",
      "nav": "Recordatorios de hora",
      "html": "<p>Obtén una hora con un desfase fijo respecto a una hora de referencia — útil para alarmas y recordatorios.</p>\n<div class=\"help-example\" data-expr=\"wake = 6:30 am\nwake + 45 minutes\nwake + 8 hours\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">07:15 y 14:30</span></div>"
    },
    {
      "id": "examples-presupuesto-del-hogar-por-categoria",
      "nav": "Presupuesto del hogar por categoría",
      "html": "<p>Etiqueta cada gasto con una categoría; una línea que solo tiene la tag totaliza esa categoría, y las tags también se suman.</p>\n<div class=\"help-example\" data-expr=\"Budget:\nrent: 1200 #home\nutilities: 150 #home\ngroceries: 480 #living\ntransport: 120 #living\nend\n#home\n#living\n#home + #living\" tabindex=\"0\" role=\"button\"><code></code><span class=\"help-returns\">cada #tag es un total de categoría; la última las suma</span></div>"
    }
  ]
};
